# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - alert-hub-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://alerthubregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cbf15a7de91446bfb63e27f4632dfe8c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f9de2dc99a0b46afae96638552c416a9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: alerthubregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cbf15a7de91446bfb63e27f4632dfe8c }}/alerthubregistry/alerthubregistry/alert-hub-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alert-hub-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c6a7940d2af94f0990b4480131fda046 }}
        images: 'alerthubregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cbf15a7de91446bfb63e27f4632dfe8c }}/alerthubregistry/alerthubregistry/alert-hub-frontend:${{ github.sha }}'